from setuptools import setup

setup(
    name='00_CodeGenerator',
    version='V0.4.0',
    packages=['venv.lib.python3.6.distutils', 'venv.lib.python3.6.encodings', 'venv.lib.python3.6.importlib',
              'venv.lib.python3.6.collections', 'venv.lib.python3.6.site-packages.PIL',
              'venv.lib.python3.6.site-packages.pip', 'venv.lib.python3.6.site-packages.pip._vendor',
              'venv.lib.python3.6.site-packages.pip._vendor.idna',
              'venv.lib.python3.6.site-packages.pip._vendor.pep517',
              'venv.lib.python3.6.site-packages.pip._vendor.pytoml',
              'venv.lib.python3.6.site-packages.pip._vendor.certifi',
              'venv.lib.python3.6.site-packages.pip._vendor.chardet',
              'venv.lib.python3.6.site-packages.pip._vendor.chardet.cli',
              'venv.lib.python3.6.site-packages.pip._vendor.distlib',
              'venv.lib.python3.6.site-packages.pip._vendor.distlib._backport',
              'venv.lib.python3.6.site-packages.pip._vendor.msgpack',
              'venv.lib.python3.6.site-packages.pip._vendor.urllib3',
              'venv.lib.python3.6.site-packages.pip._vendor.urllib3.util',
              'venv.lib.python3.6.site-packages.pip._vendor.urllib3.contrib',
              'venv.lib.python3.6.site-packages.pip._vendor.urllib3.contrib._securetransport',
              'venv.lib.python3.6.site-packages.pip._vendor.urllib3.packages',
              'venv.lib.python3.6.site-packages.pip._vendor.urllib3.packages.backports',
              'venv.lib.python3.6.site-packages.pip._vendor.urllib3.packages.ssl_match_hostname',
              'venv.lib.python3.6.site-packages.pip._vendor.colorama',
              'venv.lib.python3.6.site-packages.pip._vendor.html5lib',
              'venv.lib.python3.6.site-packages.pip._vendor.html5lib._trie',
              'venv.lib.python3.6.site-packages.pip._vendor.html5lib.filters',
              'venv.lib.python3.6.site-packages.pip._vendor.html5lib.treewalkers',
              'venv.lib.python3.6.site-packages.pip._vendor.html5lib.treeadapters',
              'venv.lib.python3.6.site-packages.pip._vendor.html5lib.treebuilders',
              'venv.lib.python3.6.site-packages.pip._vendor.lockfile',
              'venv.lib.python3.6.site-packages.pip._vendor.progress',
              'venv.lib.python3.6.site-packages.pip._vendor.requests',
              'venv.lib.python3.6.site-packages.pip._vendor.packaging',
              'venv.lib.python3.6.site-packages.pip._vendor.cachecontrol',
              'venv.lib.python3.6.site-packages.pip._vendor.cachecontrol.caches',
              'venv.lib.python3.6.site-packages.pip._vendor.webencodings',
              'venv.lib.python3.6.site-packages.pip._vendor.pkg_resources',
              'venv.lib.python3.6.site-packages.pip._internal', 'venv.lib.python3.6.site-packages.pip._internal.cli',
              'venv.lib.python3.6.site-packages.pip._internal.req',
              'venv.lib.python3.6.site-packages.pip._internal.vcs',
              'venv.lib.python3.6.site-packages.pip._internal.utils',
              'venv.lib.python3.6.site-packages.pip._internal.models',
              'venv.lib.python3.6.site-packages.pip._internal.commands',
              'venv.lib.python3.6.site-packages.pip._internal.operations', 'venv.lib.python3.6.site-packages.pytz',
              'venv.lib.python3.6.site-packages.xlrd', 'venv.lib.python3.6.site-packages.numpy',
              'venv.lib.python3.6.site-packages.numpy.ma', 'venv.lib.python3.6.site-packages.numpy.ma.tests',
              'venv.lib.python3.6.site-packages.numpy.doc', 'venv.lib.python3.6.site-packages.numpy.fft',
              'venv.lib.python3.6.site-packages.numpy.fft.tests', 'venv.lib.python3.6.site-packages.numpy.lib',
              'venv.lib.python3.6.site-packages.numpy.lib.tests', 'venv.lib.python3.6.site-packages.numpy.core',
              'venv.lib.python3.6.site-packages.numpy.core.tests', 'venv.lib.python3.6.site-packages.numpy.f2py',
              'venv.lib.python3.6.site-packages.numpy.f2py.tests', 'venv.lib.python3.6.site-packages.numpy.tests',
              'venv.lib.python3.6.site-packages.numpy.compat', 'venv.lib.python3.6.site-packages.numpy.compat.tests',
              'venv.lib.python3.6.site-packages.numpy.linalg', 'venv.lib.python3.6.site-packages.numpy.linalg.tests',
              'venv.lib.python3.6.site-packages.numpy.random', 'venv.lib.python3.6.site-packages.numpy.random.tests',
              'venv.lib.python3.6.site-packages.numpy.testing', 'venv.lib.python3.6.site-packages.numpy.testing.tests',
              'venv.lib.python3.6.site-packages.numpy.testing._private',
              'venv.lib.python3.6.site-packages.numpy.distutils',
              'venv.lib.python3.6.site-packages.numpy.distutils.tests',
              'venv.lib.python3.6.site-packages.numpy.distutils.command',
              'venv.lib.python3.6.site-packages.numpy.distutils.fcompiler',
              'venv.lib.python3.6.site-packages.numpy.matrixlib',
              'venv.lib.python3.6.site-packages.numpy.matrixlib.tests',
              'venv.lib.python3.6.site-packages.numpy.polynomial',
              'venv.lib.python3.6.site-packages.numpy.polynomial.tests', 'venv.lib.python3.6.site-packages.wheel',
              'venv.lib.python3.6.site-packages.wheel.cli', 'venv.lib.python3.6.site-packages.pandas',
              'venv.lib.python3.6.site-packages.pandas.io', 'venv.lib.python3.6.site-packages.pandas.io.sas',
              'venv.lib.python3.6.site-packages.pandas.io.json', 'venv.lib.python3.6.site-packages.pandas.io.formats',
              'venv.lib.python3.6.site-packages.pandas.io.msgpack',
              'venv.lib.python3.6.site-packages.pandas.io.clipboard', 'venv.lib.python3.6.site-packages.pandas.api',
              'venv.lib.python3.6.site-packages.pandas.api.types',
              'venv.lib.python3.6.site-packages.pandas.api.extensions', 'venv.lib.python3.6.site-packages.pandas.core',
              'venv.lib.python3.6.site-packages.pandas.core.util', 'venv.lib.python3.6.site-packages.pandas.core.tools',
              'venv.lib.python3.6.site-packages.pandas.core.arrays',
              'venv.lib.python3.6.site-packages.pandas.core.dtypes',
              'venv.lib.python3.6.site-packages.pandas.core.sparse',
              'venv.lib.python3.6.site-packages.pandas.core.groupby',
              'venv.lib.python3.6.site-packages.pandas.core.indexes',
              'venv.lib.python3.6.site-packages.pandas.core.reshape',
              'venv.lib.python3.6.site-packages.pandas.core.computation',
              'venv.lib.python3.6.site-packages.pandas.util', 'venv.lib.python3.6.site-packages.pandas._libs',
              'venv.lib.python3.6.site-packages.pandas._libs.tslibs', 'venv.lib.python3.6.site-packages.pandas.tests',
              'venv.lib.python3.6.site-packages.pandas.tests.io',
              'venv.lib.python3.6.site-packages.pandas.tests.io.sas',
              'venv.lib.python3.6.site-packages.pandas.tests.io.json',
              'venv.lib.python3.6.site-packages.pandas.tests.io.parser',
              'venv.lib.python3.6.site-packages.pandas.tests.io.formats',
              'venv.lib.python3.6.site-packages.pandas.tests.io.msgpack',
              'venv.lib.python3.6.site-packages.pandas.tests.api', 'venv.lib.python3.6.site-packages.pandas.tests.util',
              'venv.lib.python3.6.site-packages.pandas.tests.frame',
              'venv.lib.python3.6.site-packages.pandas.tests.tools',
              'venv.lib.python3.6.site-packages.pandas.tests.dtypes',
              'venv.lib.python3.6.site-packages.pandas.tests.scalar',
              'venv.lib.python3.6.site-packages.pandas.tests.scalar.period',
              'venv.lib.python3.6.site-packages.pandas.tests.scalar.interval',
              'venv.lib.python3.6.site-packages.pandas.tests.scalar.timedelta',
              'venv.lib.python3.6.site-packages.pandas.tests.scalar.timestamp',
              'venv.lib.python3.6.site-packages.pandas.tests.series',
              'venv.lib.python3.6.site-packages.pandas.tests.series.indexing',
              'venv.lib.python3.6.site-packages.pandas.tests.sparse',
              'venv.lib.python3.6.site-packages.pandas.tests.sparse.frame',
              'venv.lib.python3.6.site-packages.pandas.tests.sparse.series',
              'venv.lib.python3.6.site-packages.pandas.tests.tslibs',
              'venv.lib.python3.6.site-packages.pandas.tests.generic',
              'venv.lib.python3.6.site-packages.pandas.tests.groupby',
              'venv.lib.python3.6.site-packages.pandas.tests.groupby.aggregate',
              'venv.lib.python3.6.site-packages.pandas.tests.indexes',
              'venv.lib.python3.6.site-packages.pandas.tests.indexes.period',
              'venv.lib.python3.6.site-packages.pandas.tests.indexes.interval',
              'venv.lib.python3.6.site-packages.pandas.tests.indexes.datetimes',
              'venv.lib.python3.6.site-packages.pandas.tests.indexes.timedeltas',
              'venv.lib.python3.6.site-packages.pandas.tests.reshape',
              'venv.lib.python3.6.site-packages.pandas.tests.reshape.merge',
              'venv.lib.python3.6.site-packages.pandas.tests.tseries',
              'venv.lib.python3.6.site-packages.pandas.tests.tseries.offsets',
              'venv.lib.python3.6.site-packages.pandas.tests.indexing',
              'venv.lib.python3.6.site-packages.pandas.tests.indexing.interval',
              'venv.lib.python3.6.site-packages.pandas.tests.plotting',
              'venv.lib.python3.6.site-packages.pandas.tests.extension',
              'venv.lib.python3.6.site-packages.pandas.tests.extension.base',
              'venv.lib.python3.6.site-packages.pandas.tests.extension.json',
              'venv.lib.python3.6.site-packages.pandas.tests.extension.decimal',
              'venv.lib.python3.6.site-packages.pandas.tests.extension.category',
              'venv.lib.python3.6.site-packages.pandas.tests.internals',
              'venv.lib.python3.6.site-packages.pandas.tests.categorical',
              'venv.lib.python3.6.site-packages.pandas.tests.computation',
              'venv.lib.python3.6.site-packages.pandas.tools', 'venv.lib.python3.6.site-packages.pandas.types',
              'venv.lib.python3.6.site-packages.pandas.compat', 'venv.lib.python3.6.site-packages.pandas.compat.numpy',
              'venv.lib.python3.6.site-packages.pandas.errors', 'venv.lib.python3.6.site-packages.pandas.formats',
              'venv.lib.python3.6.site-packages.pandas.tseries', 'venv.lib.python3.6.site-packages.pandas.plotting',
              'venv.lib.python3.6.site-packages.pandas.computation', 'venv.lib.python3.6.site-packages.pubsub',
              'venv.lib.python3.6.site-packages.pubsub.core', 'venv.lib.python3.6.site-packages.pubsub.utils',
              'venv.lib.python3.6.site-packages.dateutil', 'venv.lib.python3.6.site-packages.dateutil.tz',
              'venv.lib.python3.6.site-packages.dateutil.parser', 'venv.lib.python3.6.site-packages.dateutil.zoneinfo',
              'venv.lib.python3.6.site-packages.setuptools', 'venv.lib.python3.6.site-packages.setuptools.extern',
              'venv.lib.python3.6.site-packages.setuptools._vendor',
              'venv.lib.python3.6.site-packages.setuptools._vendor.packaging',
              'venv.lib.python3.6.site-packages.setuptools.command', 'venv.lib.python3.6.site-packages.pkg_resources',
              'venv.lib.python3.6.site-packages.pkg_resources.extern',
              'venv.lib.python3.6.site-packages.pkg_resources._vendor',
              'venv.lib.python3.6.site-packages.pkg_resources._vendor.packaging', 'venv1.lib.python3.6.distutils',
              'venv1.lib.python3.6.encodings', 'venv1.lib.python3.6.importlib', 'venv1.lib.python3.6.collections',
              'venv1.lib.python3.6.site-packages.pip', 'venv1.lib.python3.6.site-packages.pip._vendor',
              'venv1.lib.python3.6.site-packages.pip._vendor.idna',
              'venv1.lib.python3.6.site-packages.pip._vendor.pep517',
              'venv1.lib.python3.6.site-packages.pip._vendor.pytoml',
              'venv1.lib.python3.6.site-packages.pip._vendor.certifi',
              'venv1.lib.python3.6.site-packages.pip._vendor.chardet',
              'venv1.lib.python3.6.site-packages.pip._vendor.chardet.cli',
              'venv1.lib.python3.6.site-packages.pip._vendor.distlib',
              'venv1.lib.python3.6.site-packages.pip._vendor.distlib._backport',
              'venv1.lib.python3.6.site-packages.pip._vendor.msgpack',
              'venv1.lib.python3.6.site-packages.pip._vendor.urllib3',
              'venv1.lib.python3.6.site-packages.pip._vendor.urllib3.util',
              'venv1.lib.python3.6.site-packages.pip._vendor.urllib3.contrib',
              'venv1.lib.python3.6.site-packages.pip._vendor.urllib3.contrib._securetransport',
              'venv1.lib.python3.6.site-packages.pip._vendor.urllib3.packages',
              'venv1.lib.python3.6.site-packages.pip._vendor.urllib3.packages.backports',
              'venv1.lib.python3.6.site-packages.pip._vendor.urllib3.packages.ssl_match_hostname',
              'venv1.lib.python3.6.site-packages.pip._vendor.colorama',
              'venv1.lib.python3.6.site-packages.pip._vendor.html5lib',
              'venv1.lib.python3.6.site-packages.pip._vendor.html5lib._trie',
              'venv1.lib.python3.6.site-packages.pip._vendor.html5lib.filters',
              'venv1.lib.python3.6.site-packages.pip._vendor.html5lib.treewalkers',
              'venv1.lib.python3.6.site-packages.pip._vendor.html5lib.treeadapters',
              'venv1.lib.python3.6.site-packages.pip._vendor.html5lib.treebuilders',
              'venv1.lib.python3.6.site-packages.pip._vendor.lockfile',
              'venv1.lib.python3.6.site-packages.pip._vendor.progress',
              'venv1.lib.python3.6.site-packages.pip._vendor.requests',
              'venv1.lib.python3.6.site-packages.pip._vendor.packaging',
              'venv1.lib.python3.6.site-packages.pip._vendor.cachecontrol',
              'venv1.lib.python3.6.site-packages.pip._vendor.cachecontrol.caches',
              'venv1.lib.python3.6.site-packages.pip._vendor.webencodings',
              'venv1.lib.python3.6.site-packages.pip._vendor.pkg_resources',
              'venv1.lib.python3.6.site-packages.pip._internal', 'venv1.lib.python3.6.site-packages.pip._internal.cli',
              'venv1.lib.python3.6.site-packages.pip._internal.req',
              'venv1.lib.python3.6.site-packages.pip._internal.vcs',
              'venv1.lib.python3.6.site-packages.pip._internal.utils',
              'venv1.lib.python3.6.site-packages.pip._internal.models',
              'venv1.lib.python3.6.site-packages.pip._internal.commands',
              'venv1.lib.python3.6.site-packages.pip._internal.operations', 'venv1.lib.python3.6.site-packages.isort',
              'venv1.lib.python3.6.site-packages.wheel', 'venv1.lib.python3.6.site-packages.wheel.cli',
              'venv1.lib.python3.6.site-packages.wrapt', 'venv1.lib.python3.6.site-packages.pylint',
              'venv1.lib.python3.6.site-packages.pylint.test.data',
              'venv1.lib.python3.6.site-packages.pylint.test.input',
              'venv1.lib.python3.6.site-packages.pylint.test.input.func_w0401_package',
              'venv1.lib.python3.6.site-packages.pylint.test.extensions',
              'venv1.lib.python3.6.site-packages.pylint.test.functional',
              'venv1.lib.python3.6.site-packages.pylint.test.regrtest_data.dummy',
              'venv1.lib.python3.6.site-packages.pylint.test.regrtest_data.absimp',
              'venv1.lib.python3.6.site-packages.pylint.test.regrtest_data.package',
              'venv1.lib.python3.6.site-packages.pylint.test.regrtest_data.package.subpackage',
              'venv1.lib.python3.6.site-packages.pylint.test.regrtest_data.beyond_top',
              'venv1.lib.python3.6.site-packages.pylint.test.regrtest_data.bad_package',
              'venv1.lib.python3.6.site-packages.pylint.test.regrtest_data.package_all',
              'venv1.lib.python3.6.site-packages.pylint.test.regrtest_data.init_wildcard',
              'venv1.lib.python3.6.site-packages.pylint.checkers', 'venv1.lib.python3.6.site-packages.pylint.pyreverse',
              'venv1.lib.python3.6.site-packages.pylint.reporters',
              'venv1.lib.python3.6.site-packages.pylint.reporters.ureports',
              'venv1.lib.python3.6.site-packages.pylint.extensions', 'venv1.lib.python3.6.site-packages.astroid',
              'venv1.lib.python3.6.site-packages.astroid.interpreter',
              'venv1.lib.python3.6.site-packages.astroid.interpreter._import',
              'venv1.lib.python3.6.site-packages.typed_ast', 'venv1.lib.python3.6.site-packages.setuptools',
              'venv1.lib.python3.6.site-packages.setuptools.extern',
              'venv1.lib.python3.6.site-packages.setuptools._vendor',
              'venv1.lib.python3.6.site-packages.setuptools._vendor.packaging',
              'venv1.lib.python3.6.site-packages.setuptools.command', 'venv1.lib.python3.6.site-packages.pkg_resources',
              'venv1.lib.python3.6.site-packages.pkg_resources.extern',
              'venv1.lib.python3.6.site-packages.pkg_resources._vendor',
              'venv1.lib.python3.6.site-packages.pkg_resources._vendor.packaging',
              'venv1.lib.python3.6.site-packages.lazy_object_proxy', 'CodeGenerator', 'CodeGenerator.conf',
              'CodeGenerator.generators'],
    url='http://www.dgrill.at/',
    license='MIT',
    author='dgrill',
    author_email='dgrill@dgrill.at',
    description='-'
)
