//***********************************************
// Codegenerator BuR V0.9.0
// by dgrill
// http://www.dgrill.at
// dgrill@dgrill.at
// Date of generation: 14.12.2018 22:34
//***********************************************

//***********************************************
// Standard FB FB1
//***********************************************

Object1(
	IN_Prm_0 := "Prm0",
	IN_Prm_1 := "Prm1",
	IN_Prm_2 := "Prm2",
	IN_Prm_3 := "Prm3",
	IN_Prm_4 := "Prm4",
	Object_struct := "DB_FB_Std".Object1);

	"Prm5" := Object1.OUT_Prm_0; 
	"Prm6" := Object1.OUT_Prm_1; 
	"Prm7" := Object1.OUT_Prm_2; 
	"Prm8" := Object1.OUT_Prm_3; 
	"Prm9" := Object1.OUT_Prm_4; 

//***********************************************
// Standard FB FB2
//***********************************************

Object2(
	IN_Prm_0 := "Prm0",
	IN_Prm_1 := "Prm1",
	IN_Prm_2 := "Prm2",
	IN_Prm_3 := "Prm3",
	IN_Prm_4 := "Prm4",
	Object_struct := "DB_FB_Std".Object2);

	"Prm5" := Object2.OUT_Prm_0; 
	"Prm6" := Object2.OUT_Prm_1; 
	"Prm7" := Object2.OUT_Prm_2; 
	"Prm8" := Object2.OUT_Prm_3; 
	"Prm9" := Object2.OUT_Prm_4; 

//***********************************************
// Standard FB FB3
//***********************************************

Object3(
	IN_Prm_0 := "Prm0",
	IN_Prm_1 := "Prm1",
	IN_Prm_2 := "Prm2",
	IN_Prm_3 := "Prm3",
	IN_Prm_4 := "Prm4",
	Object_struct := "DB_FB_Std".Object3);

	"Prm5" := Object3.OUT_Prm_0; 
	"Prm6" := Object3.OUT_Prm_1; 
	"Prm7" := Object3.OUT_Prm_2; 
	"Prm8" := Object3.OUT_Prm_3; 
	"Prm9" := Object3.OUT_Prm_4; 

//***********************************************
// Standard FB FB4
//***********************************************

Object4(
	IN_Prm_0 := "Prm0",
	IN_Prm_1 := "Prm1",
	IN_Prm_2 := "Prm2",
	IN_Prm_3 := "Prm3",
	IN_Prm_4 := "Prm4",
	Object_struct := "DB_FB_Std".Object4);

	"Prm5" := Object4.OUT_Prm_0; 
	"Prm6" := Object4.OUT_Prm_1; 
	"Prm7" := Object4.OUT_Prm_2; 
	"Prm8" := Object4.OUT_Prm_3; 
	"Prm9" := Object4.OUT_Prm_4; 

//***********************************************
// Standard FB FB5
//***********************************************

Object5(
	IN_Prm_0 := "Prm0",
	IN_Prm_1 := "Prm1",
	IN_Prm_2 := "Prm2",
	IN_Prm_3 := "Prm3",
	IN_Prm_4 := "Prm4",
	Object_struct := "DB_FB_Std".Object5);

	"Prm5" := Object5.OUT_Prm_0; 
	"Prm6" := Object5.OUT_Prm_1; 
	"Prm7" := Object5.OUT_Prm_2; 
	"Prm8" := Object5.OUT_Prm_3; 
	"Prm9" := Object5.OUT_Prm_4; 

//***********************************************
// Standard FB FB6
//***********************************************

Object6(
	IN_Prm_0 := "Prm0",
	IN_Prm_1 := "Prm1",
	IN_Prm_2 := "Prm2",
	IN_Prm_3 := "Prm3",
	IN_Prm_4 := "Prm4",
	Object_struct := "DB_FB_Std".Object6);

	"Prm5" := Object6.OUT_Prm_0; 
	"Prm6" := Object6.OUT_Prm_1; 
	"Prm7" := Object6.OUT_Prm_2; 
	"Prm8" := Object6.OUT_Prm_3; 
	"Prm9" := Object6.OUT_Prm_4; 

//***********************************************
// Standard FB FB7
//***********************************************

Object7(
	IN_Prm_0 := "Prm0",
	IN_Prm_1 := "Prm1",
	IN_Prm_2 := "Prm2",
	IN_Prm_3 := "Prm3",
	IN_Prm_4 := "Prm4",
	Object_struct := "DB_FB_Std".Object7);

	"Prm5" := Object7.OUT_Prm_0; 
	"Prm6" := Object7.OUT_Prm_1; 
	"Prm7" := Object7.OUT_Prm_2; 
	"Prm8" := Object7.OUT_Prm_3; 
	"Prm9" := Object7.OUT_Prm_4; 

//***********************************************
// Standard FB FB8
//***********************************************

Object8(
	IN_Prm_0 := "Prm0",
	IN_Prm_1 := "Prm1",
	IN_Prm_2 := "Prm2",
	IN_Prm_3 := "Prm3",
	IN_Prm_4 := "Prm4",
	Object_struct := "DB_FB_Std".Object8);

	"Prm5" := Object8.OUT_Prm_0; 
	"Prm6" := Object8.OUT_Prm_1; 
	"Prm7" := Object8.OUT_Prm_2; 
	"Prm8" := Object8.OUT_Prm_3; 
	"Prm9" := Object8.OUT_Prm_4; 

//***********************************************
// Standard FB FB9
//***********************************************

Object9(
	IN_Prm_0 := "Prm0",
	IN_Prm_1 := "Prm1",
	IN_Prm_2 := "Prm2",
	IN_Prm_3 := "Prm3",
	IN_Prm_4 := "Prm4",
	Object_struct := "DB_FB_Std".Object9);

	"Prm5" := Object9.OUT_Prm_0; 
	"Prm6" := Object9.OUT_Prm_1; 
	"Prm7" := Object9.OUT_Prm_2; 
	"Prm8" := Object9.OUT_Prm_3; 
	"Prm9" := Object9.OUT_Prm_4; 

//***********************************************
// Standard FB FB10
//***********************************************

Object10(
	IN_Prm_0 := "Prm0",
	IN_Prm_1 := "Prm1",
	IN_Prm_2 := "Prm2",
	IN_Prm_3 := "Prm3",
	IN_Prm_4 := "Prm4",
	Object_struct := "DB_FB_Std".Object10);

	"Prm5" := Object10.OUT_Prm_0; 
	"Prm6" := Object10.OUT_Prm_1; 
	"Prm7" := Object10.OUT_Prm_2; 
	"Prm8" := Object10.OUT_Prm_3; 
	"Prm9" := Object10.OUT_Prm_4; 

//***********************************************
// Standard FB FB11
//***********************************************

Object11(
	IN_Prm_0 := "Prm0",
	IN_Prm_1 := "Prm1",
	IN_Prm_2 := "Prm2",
	IN_Prm_3 := "Prm3",
	IN_Prm_4 := "Prm4",
	Object_struct := "DB_FB_Std".Object11);

	"Prm5" := Object11.OUT_Prm_0; 
	"Prm6" := Object11.OUT_Prm_1; 
	"Prm7" := Object11.OUT_Prm_2; 
	"Prm8" := Object11.OUT_Prm_3; 
	"Prm9" := Object11.OUT_Prm_4; 

//***********************************************
// Standard FB FB12
//***********************************************

Object12(
	IN_Prm_0 := "Prm0",
	IN_Prm_1 := "Prm1",
	IN_Prm_2 := "Prm2",
	IN_Prm_3 := "Prm3",
	IN_Prm_4 := "Prm4",
	Object_struct := "DB_FB_Std".Object12);

	"Prm5" := Object12.OUT_Prm_0; 
	"Prm6" := Object12.OUT_Prm_1; 
	"Prm7" := Object12.OUT_Prm_2; 
	"Prm8" := Object12.OUT_Prm_3; 
	"Prm9" := Object12.OUT_Prm_4; 

//***********************************************
// Standard FB FB13
//***********************************************

Object13(
	IN_Prm_0 := "Prm0",
	IN_Prm_1 := "Prm1",
	IN_Prm_2 := "Prm2",
	IN_Prm_3 := "Prm3",
	IN_Prm_4 := "Prm4",
	Object_struct := "DB_FB_Std".Object13);

	"Prm5" := Object13.OUT_Prm_0; 
	"Prm6" := Object13.OUT_Prm_1; 
	"Prm7" := Object13.OUT_Prm_2; 
	"Prm8" := Object13.OUT_Prm_3; 
	"Prm9" := Object13.OUT_Prm_4; 

//***********************************************
// Standard FB FB14
//***********************************************

Object14(
	IN_Prm_0 := "Prm0",
	IN_Prm_1 := "Prm1",
	IN_Prm_2 := "Prm2",
	IN_Prm_3 := "Prm3",
	IN_Prm_4 := "Prm4",
	Object_struct := "DB_FB_Std".Object14);

	"Prm5" := Object14.OUT_Prm_0; 
	"Prm6" := Object14.OUT_Prm_1; 
	"Prm7" := Object14.OUT_Prm_2; 
	"Prm8" := Object14.OUT_Prm_3; 
	"Prm9" := Object14.OUT_Prm_4; 

//***********************************************
// Standard FB FB15
//***********************************************

Object15(
	IN_Prm_0 := "Prm0",
	IN_Prm_1 := "Prm1",
	IN_Prm_2 := "Prm2",
	IN_Prm_3 := "Prm3",
	IN_Prm_4 := "Prm4",
	Object_struct := "DB_FB_Std".Object15);

	"Prm5" := Object15.OUT_Prm_0; 
	"Prm6" := Object15.OUT_Prm_1; 
	"Prm7" := Object15.OUT_Prm_2; 
	"Prm8" := Object15.OUT_Prm_3; 
	"Prm9" := Object15.OUT_Prm_4; 

//***********************************************
// Standard FB FB16
//***********************************************

Object16(
	IN_Prm_0 := "Prm0",
	IN_Prm_1 := "Prm1",
	IN_Prm_2 := "Prm2",
	IN_Prm_3 := "Prm3",
	IN_Prm_4 := "Prm4",
	Object_struct := "DB_FB_Std".Object16);

	"Prm5" := Object16.OUT_Prm_0; 
	"Prm6" := Object16.OUT_Prm_1; 
	"Prm7" := Object16.OUT_Prm_2; 
	"Prm8" := Object16.OUT_Prm_3; 
	"Prm9" := Object16.OUT_Prm_4; 

//***********************************************
// Standard FB FB17
//***********************************************

Object17(
	IN_Prm_0 := "Prm0",
	IN_Prm_1 := "Prm1",
	IN_Prm_2 := "Prm2",
	IN_Prm_3 := "Prm3",
	IN_Prm_4 := "Prm4",
	Object_struct := "DB_FB_Std".Object17);

	"Prm5" := Object17.OUT_Prm_0; 
	"Prm6" := Object17.OUT_Prm_1; 
	"Prm7" := Object17.OUT_Prm_2; 
	"Prm8" := Object17.OUT_Prm_3; 
	"Prm9" := Object17.OUT_Prm_4; 

//***********************************************
// Standard FB FB18
//***********************************************

Object18(
	IN_Prm_0 := "Prm0",
	IN_Prm_1 := "Prm1",
	IN_Prm_2 := "Prm2",
	IN_Prm_3 := "Prm3",
	IN_Prm_4 := "Prm4",
	Object_struct := "DB_FB_Std".Object18);

	"Prm5" := Object18.OUT_Prm_0; 
	"Prm6" := Object18.OUT_Prm_1; 
	"Prm7" := Object18.OUT_Prm_2; 
	"Prm8" := Object18.OUT_Prm_3; 
	"Prm9" := Object18.OUT_Prm_4; 

//***********************************************
// Standard FB FB19
//***********************************************

Object19(
	IN_Prm_0 := "Prm0",
	IN_Prm_1 := "Prm1",
	IN_Prm_2 := "Prm2",
	IN_Prm_3 := "Prm3",
	IN_Prm_4 := "Prm4",
	Object_struct := "DB_FB_Std".Object19);

	"Prm5" := Object19.OUT_Prm_0; 
	"Prm6" := Object19.OUT_Prm_1; 
	"Prm7" := Object19.OUT_Prm_2; 
	"Prm8" := Object19.OUT_Prm_3; 
	"Prm9" := Object19.OUT_Prm_4; 

//***********************************************
// Standard FB FB20
//***********************************************

Object20(
	IN_Prm_0 := "Prm0",
	IN_Prm_1 := "Prm1",
	IN_Prm_2 := "Prm2",
	IN_Prm_3 := "Prm3",
	IN_Prm_4 := "Prm4",
	Object_struct := "DB_FB_Std".Object20);

	"Prm5" := Object20.OUT_Prm_0; 
	"Prm6" := Object20.OUT_Prm_1; 
	"Prm7" := Object20.OUT_Prm_2; 
	"Prm8" := Object20.OUT_Prm_3; 
	"Prm9" := Object20.OUT_Prm_4; 

//***********************************************
// Standard FB FB21
//***********************************************

Object21(
	IN_Prm_0 := "Prm0",
	IN_Prm_1 := "Prm1",
	IN_Prm_2 := "Prm2",
	IN_Prm_3 := "Prm3",
	IN_Prm_4 := "Prm4",
	Object_struct := "DB_FB_Std".Object21);

	"Prm5" := Object21.OUT_Prm_0; 
	"Prm6" := Object21.OUT_Prm_1; 
	"Prm7" := Object21.OUT_Prm_2; 
	"Prm8" := Object21.OUT_Prm_3; 
	"Prm9" := Object21.OUT_Prm_4; 

//***********************************************
// Standard FB FB22
//***********************************************

Object22(
	IN_Prm_0 := "Prm0",
	IN_Prm_1 := "Prm1",
	IN_Prm_2 := "Prm2",
	IN_Prm_3 := "Prm3",
	IN_Prm_4 := "Prm4",
	Object_struct := "DB_FB_Std".Object22);

	"Prm5" := Object22.OUT_Prm_0; 
	"Prm6" := Object22.OUT_Prm_1; 
	"Prm7" := Object22.OUT_Prm_2; 
	"Prm8" := Object22.OUT_Prm_3; 
	"Prm9" := Object22.OUT_Prm_4; 

