//***********************************************
// FB_Std
// Author: dgrill
// Version: 1.0
// Date: 06.12.2018 23:06
// Description: 
// 
// Interface: 
// VAR_INPUT:
// IN_Prm_0:	BOOL	Input Parameter 1
// IN_Prm_1:	BOOL	Input Parameter 2
// IN_Prm_2:	BOOL	Input Parameter 3
// IN_Prm_3:	BOOL	Input Parameter 4
// IN_Prm_4:	BOOL	Input Parameter 5
// 
// VAR_OUTPUT:
// OUT_Prm_0:	BOOL	Output Parameter 1
// OUT_Prm_1:	BOOL	Output Parameter 2
// OUT_Prm_2:	BOOL	Output Parameter 3
// OUT_Prm_3:	BOOL	Output Parameter 4
// OUT_Prm_4:	BOOL	Output Parameter 5
// 
// VAR_IN_OUT:
// Object_struct:	TYP_FB_Std	Objectstrucuture
// 
// Rev: 
// 
//***********************************************

FUNCTION_BLOCK  FB_Std

// TODO - Insert Code here

END_FUNCTION_BLOCK