//***********************************************
// FB_Std
// Author: dgrill
// Version: V1.0.0
// Date: 27.11.2018 21:45
// Description: 
// 
// Interface: 
// VAR_INPUT:
// Enable:	BOOL	Bausteinfreigabe
// MSS:	BOOL	MSS OK
// 
// VAR_OUTPUT:
// O_Forward:	BOOL	Forderband vorwaerts ein
// O_Backward:	BOOL	Forderband rueckwaerts ein
// 
// VAR_IN_OUT:
// ObjectStruct:	TYP_FB_Std	Type of FB Std
// 
// Rev: 
// 
//***********************************************

FUNCTION_BLOCK FB_Std

// TODO - Insert Code here

END_FUNCTION_BLOCK