//***********************************************
// Codegenerator BuR V0.9.0
// by dgrill
// http://www.dgrill.at
// dgrill@dgrill.at
// Date of generation: 27.11.2018 21:45
//***********************************************

//***********************************************
// Förderband 1   =HV1+M1
//***********************************************
FB1(
	Enable := True,
	MSS := _15A1.DI1,
	Length := 250.0,
	O_Forward := A10.0,
	O_Backward := A11.0,
	ObjectStruct := FB1);

//***********************************************
// Förderband 2  =HV1+M2
//***********************************************
FB2(
	Enable := True,
	MSS := _15A1.DI2,
	Length := 260.0,
	O_Forward := A10.1,
	O_Backward := A11.1,
	ObjectStruct := FB2);

//***********************************************
// Förderband 3  =HV1+M3
//***********************************************
FB3(
	Enable := True,
	MSS := _15A1.DI3,
	Length := 270.0,
	O_Forward := A10.2,
	O_Backward := A11.2,
	ObjectStruct := FB3);

//***********************************************
// Förderband 4 Steigförderband  =HV1+M4
//***********************************************
FB4(
	Enable := True,
	MSS := _15A1.DI4,
	Length := 270.1,
	O_Forward := A10.3,
	O_Backward := A11.3,
	ObjectStruct := FB4);

//***********************************************
// Förderband 5  =HV1+M5
//***********************************************
FB5(
	Enable := True,
	MSS := _15A1.DI5,
	Length := 270.2,
	O_Forward := A10.4,
	O_Backward := A11.4,
	ObjectStruct := FB5);

//***********************************************
// Förderband 6  =HV1+M6
//***********************************************
FB6(
	Enable := True,
	MSS := _15A1.DI6,
	Length := 270.3,
	O_Forward := A10.5,
	O_Backward := A11.5,
	ObjectStruct := FB6);

//***********************************************
// Förderband 7  =HV1+M7
//***********************************************
FB7(
	Enable := True,
	MSS := _15A1.DI7,
	Length := 270.4,
	O_Forward := A10.6,
	O_Backward := A11.6,
	ObjectStruct := FB7);

//***********************************************
// Förderband 8  =HV1+M8
//***********************************************
FB8(
	Enable := True,
	MSS := _15A1.DI8,
	Length := 270.5,
	O_Forward := A10.7,
	O_Backward := A11.7,
	ObjectStruct := FB8);

//***********************************************
// Förderband 9  =HV1+M9
//***********************************************
FB9(
	Enable := True,
	MSS := _15A1.DI9,
	Length := 270.6,
	O_Forward := A10.8,
	O_Backward := A11.8,
	ObjectStruct := FB9);

//***********************************************
// Förderband 10  =HV1+M10
//***********************************************
FB10(
	Enable := True,
	MSS := _15A1.DI10,
	Length := 270.7,
	O_Forward := A10.9,
	O_Backward := A11.9,
	ObjectStruct := FB10);

//***********************************************
// Förderband 11  =HV1+M11
//***********************************************
FB11(
	Enable := True,
	MSS := _15A1.DI10,
	Length := 270.7,
	O_Forward := A10.10,
	O_Backward := A11.10,
	ObjectStruct := FB11);

